services:
  backend:
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "8088:8088"
    networks:
      - net
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    networks:
      - net
  front:
    build:
      dockerfile: front.dockerfile
    ports:
      - "80:80"
networks:
  net: